### ISSUE TITLE
[Feature Request] Add support for assigning a default assignee

### ISSUE THREAD

**Issue by frakman1** [CVarisco/gitlab-merge#1]
There is a way through the [Gitlab HTTP API](https://docs.gitlab.com/ce/api/merge_requests.html) to assign a user for your Merge Request. Perhaps that can be an option in the .gitlab-mergerc options file.

![image](https://user-images.githubusercontent.com/5826484/48962771-1e088900-ef53-11e8-9133-f35d608ee523.png)

**Comment by CVarisco** [comment]
Hi @frakman1 !
Based on your suggestion I created a new version of the tool `v1.1.0` that add the `assignee_id` functionality.

Now, you can define also the `assignee_id` from the config:
```
{
  "assignee_id": Integer || "none"
}
```
If you don't want assignee from config, you can just use the string "none".

Otherwise, after you select the project (or already defined into the config) the tool will download the list of the project's users to select as assignee.

Thanks a lot for your suggestion.
If you have question, request or anything else, feel free to ask and contribute 😁

**Comment by frakman1** [comment]
That's great news. Thank you!

How about a further improvement?
Typically, in group development, a merge-request is assigned to different people depending on what the code is and who is responsible for what areas.
So how about one of the prompts asking you who to assign it to? Either through username or a multiple choice option? If this sounds good, I can create a new Issue/Feature Request.

**Comment by CVarisco** [comment]
> So how about one of the prompts asking you who to assign it to?

Is already like that :) You have two ways to select the assignee, from the prompt and from the config file.

> Either through username or a multiple choice option?

What do you mean with this? Because as I know there is only one assignee per MR.
Anyway, try the new version and tell me what do you think about it 👍 

Thank you 👍

**Comment by frakman1** [comment]
Excellent! I just tried it and the prompt you implemented was exactly what I had in mind. Well done!

I had another request which is to allow you to set the HTTP API option `remove_source_branch=true`. Developers often forget to set this in the Merge Request Web UI and we end up with loads of unnecessary branches that I have to later audit and manually delete. If this was set by default or with a prompt or config file option to do so, then this would make life easier.

I can make a separate Github Issue for this if you want.

Also, it would be nice if the version of `gitlab-merge` was printed somewhere in its output. Maybe even support for `gitlab-merge --version`

**Comment by CVarisco** [comment]
> I had another request which is to allow you to set the HTTP API option remove_source_branch=true

Yes, it is a good idea!
Just one thing, I suggest to use make it available only through configuration file to avoid to many questions.

> Also, it would be nice if the version of gitlab-merge was printed somewhere in its output.

What do you think after the logo on the startup?

**Comment by CVarisco** [comment]
Anyway, I created a new version where the config file is complete used [here](https://github.com/CVarisco/gitlab-merge/commit/cd507977e9691aa708a5e837d06052a2520109c4#diff-1fdf421c05c1140f6d71444ea2b27638R19) to create the merge request.
This means that now, v1.1.1 you can add the parameter that you want in the config file 👍
